version: '3'
services:
    mysql:
        image: mariadb
        ports:
            - '3306:3306'
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'Mysql.123'
            MYSQL_DATABASE: 'db_foreat'
            MYSQL_USER: 'wproot'
            MYSQL_PASSWORD: 'Wproot.123'
    wordpress:
        image: wordpress:php7.3-fpm-alpine
        volumes:
            - ./data/html:/var/www/html
        depends_on:
            - mysql
        environment:
            WORDPRESS_DB_HOST: mysql
            MYSQL_ROOT_PASSWORD: 'Mysql.123'
            WORDPRESS_DB_NAME: 'db_foreat'
            WORDPRESS_DB_USER: 'wproot'
            WORDPRESS_DB_PASSWORD: 'Wproot.123'
            WORDPRESS_TABLE_PREFIX: wp_
            MYSQL_PORT_3306_TCP: 3306
        links:
            - mysql
        restart: unless-stopped
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./data/html:/var/www/html
        ports:
            - 8080:80
        links:
            - wordpress